# ========================
# TOMCAT
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: INFO 

# ========================
# Application
# ========================
app:
  myVar: ${VAR:defaultValue}
  backgroundMaps:
    - id: ch.so.agi.hintergrundkarte_sw
      title: Hintergrundkarte schwarz-weiss
      url: https://geo.so.ch/api/wmts/1.0.0/{Layer}/default/2056/{TileMatrix}/{TileRow}/{TileCol}
      layer: ch.so.agi.hintergrundkarte_sw 
      active: true
      thumbnail: background_switcher/img/hintergrund_sw.png
    - id: ch.so.agi.hintergrundkarte_farbig
      title: Hintergrundkarte farbig    
      url: https://geo.so.ch/api/wmts/1.0.0/{Layer}/default/2056/{TileMatrix}/{TileRow}/{TileCol}
      layer: ch.so.agi.hintergrundkarte_farbig 
      active: false
      thumbnail: background_switcher/img/hintergrund_farbig.png
    - id: ch.so.agi.hintergrundkarte_ortho
      title: Luftbild    
      url: https://geo.so.ch/api/wmts/1.0.0/{Layer}/default/2056/{TileMatrix}/{TileRow}/{TileCol}
      layer: ch.so.agi.hintergrundkarte_ortho 
      active: false
      thumbnail: background_switcher/img/hintergrund_ortho.png

      
